### ISSUE TITLE
Deepl support

### ISSUE THREAD

**Issue by ni-ka** [gufoe/text-translator#38]
Great extension! How about adding support for deepl - i find it translates more natural than Google Translate. Not sure they have an API yet though.

https://www.deepl.com/en/translator

**Comment by gufoe** [comment]
Hello there!
API are available, but only under a [paid](https://www.deepl.com/pro.html#pricing) plan I think.

Anyway, this extension is not using any API directly, it is based on a command line program (translate-shell) to make translations, so it would be better to have THAT implement deepl support, so that all the programs using translate shell can benefit from it. I'll close the issue, but I invite you to open it in [their repo](https://github.com/soimort/translate-shell), it would be a nice feature!

**Comment by ni-ka** [comment]
Thanks Giacomo. I see they actually had deepl support but it was removed
again in https://github.com/soimort/translate-shell/issues/268

Thanks anyway!

-- 
Nils Kaiser
tel / whatsapp: +49 1788079029
skype: berlinils
https://www.linkedin.com/in/nilskaiser/
